name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-expo:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: build expo build image
      run: docker compose build --push

  build-apk:
    needs: build-expo

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: build apk
      - run: docker pull expo-build:latest
      - run: docker compose run expo-build
